import { NotePencil, Plus, Trash } from '@phosphor-icons/react';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import DeleteModal from '@/components/common/delete-modal';
import { PrimaryButton, SecondaryButton } from '@/components/ui/button';
import Modal from '@/components/ui/dialog';
import Input from '@/components/ui/input';
import SquareButton from '@/components/ui/squareButton';
import { Toggle } from '@/components/ui/toggle';
import { useToast } from '@/components/ui/toast';
import { getApiErrorMessage } from '@/utils/helpers';
import {
  useCreateTaskCategoryMutation,
  useCreateTaskStatusMutation,
  useDeleteTaskCategoryMutation,
  useDeleteTaskStatusMutation,
  useTaskCategoriesQuery,
  useTaskStatusesQuery,
  useUpdateTaskCategoryMutation,
  useUpdateTaskStatusMutation,
  type TaskCategoryDto,
  type TaskStatusDto,
} from '../service';

export function TaskStatusesSettings() {
  const { t } = useTranslation('projects'); const { showToast } = useToast(); const query = useTaskStatusesQuery(); const removeMutation = useDeleteTaskStatusMutation();
  const [editing, setEditing] = useState<TaskStatusDto | null>(null); const [open, setOpen] = useState(false); const [deleteItem, setDeleteItem] = useState<TaskStatusDto | null>(null);
  return <SettingsSection title={t('task_statuses')} loading={query.isLoading} onAdd={() => setOpen(true)}>{(query.data?.items ?? []).map((item) => <SettingRow key={item.id} name={item.name ?? '-'} color={item.color} details={`${item.type ?? '-'} · ${item.sortOrder}`} onEdit={() => { setEditing(item); setOpen(true); }} onDelete={item.default ? undefined : () => setDeleteItem(item)} />)}<StatusForm key={`${editing?.id ?? 'new'}-${String(open)}`} open={open} item={editing} onClose={() => { setOpen(false); setEditing(null); }} /><DeleteModal open={Boolean(deleteItem)} setOpen={(next) => !next && setDeleteItem(null)} title={t('delete')} deleteMessage={t('delete_status_confirmation')} isLoading={removeMutation.isPending} handelDelete={async () => { if (!deleteItem) return; try { await removeMutation.mutateAsync(deleteItem.id); setDeleteItem(null); } catch (error) { showToast({ variant: 'danger', description: getApiErrorMessage(error, t('operation_failed')) }); } }} /></SettingsSection>;
}

export function TaskCategoriesSettings() {
  const { t } = useTranslation('projects'); const { showToast } = useToast(); const query = useTaskCategoriesQuery(); const removeMutation = useDeleteTaskCategoryMutation();
  const [editing, setEditing] = useState<TaskCategoryDto | null>(null); const [open, setOpen] = useState(false); const [deleteItem, setDeleteItem] = useState<TaskCategoryDto | null>(null);
  return <SettingsSection title={t('task_categories')} loading={query.isLoading} onAdd={() => setOpen(true)}>{(query.data?.items ?? []).map((item) => <SettingRow key={item.id} name={item.name ?? '-'} color={item.color} details={[item.hasText && t('text'), item.hasAttachments && t('attachments'), item.hasPrices && t('prices')].filter(Boolean).join(' · ') || '-'} onEdit={() => { setEditing(item); setOpen(true); }} onDelete={() => setDeleteItem(item)} />)}<CategoryForm key={`${editing?.id ?? 'new'}-${String(open)}`} open={open} item={editing} onClose={() => { setOpen(false); setEditing(null); }} /><DeleteModal open={Boolean(deleteItem)} setOpen={(next) => !next && setDeleteItem(null)} title={t('delete')} deleteMessage={t('delete_category_confirmation')} isLoading={removeMutation.isPending} handelDelete={async () => { if (!deleteItem) return; try { await removeMutation.mutateAsync(deleteItem.id); setDeleteItem(null); } catch (error) { showToast({ variant: 'danger', description: getApiErrorMessage(error, t('operation_failed')) }); } }} /></SettingsSection>;
}

function SettingsSection({ title, loading, onAdd, children }: { title: string; loading: boolean; onAdd: () => void; children: React.ReactNode }) { const { t } = useTranslation('projects'); return <section className="space-y-4 rounded-2 border border-light-card-border bg-white p-4 dark:border-dark-card-border dark:bg-dark-card-background"><div className="flex items-center justify-between"><h2 className="font-semibold">{title}</h2><PrimaryButton icon={<Plus size={16} />} onClick={onAdd}>{t('add')}</PrimaryButton></div>{loading ? <p className="text-sm text-light-text-secondary dark:text-dark-secondary">{t('common:loading')}</p> : <div className="space-y-2">{children}</div>}</section>; }
function SettingRow({ name, color, details, onEdit, onDelete }: { name: string; color: string | null; details: string; onEdit: () => void; onDelete?: () => void }) { const { t } = useTranslation('projects'); return <div className="flex items-center justify-between gap-3 rounded-2 bg-gray-light-100 p-3 dark:bg-dark-card-surface"><div className="flex min-w-0 items-center gap-3"><span className="h-4 w-4 shrink-0 rounded-full" style={{ backgroundColor: color ?? '#3f6d6a' }} /><div className="min-w-0"><p className="truncate font-medium">{name}</p><p className="truncate text-xs text-light-text-secondary dark:text-dark-secondary">{details}</p></div></div><div className="flex gap-1"><SquareButton Icon={NotePencil} ariaLabel={t('edit')} onClick={onEdit} />{onDelete && <SquareButton Icon={Trash} ariaLabel={t('delete')} onClick={onDelete} />}</div></div>; }

function StatusForm({ open, item, onClose }: { open: boolean; item: TaskStatusDto | null; onClose: () => void }) { const { t } = useTranslation('projects'); const { showToast } = useToast(); const createMutation = useCreateTaskStatusMutation(); const updateMutation = useUpdateTaskStatusMutation(); const [values, setValues] = useState({ name: item?.name ?? '', color: item?.color ?? '#3f6d6a', type: item?.type ?? 'CUSTOM', default: item?.default ?? false, canArchive: item?.canArchive ?? false, sortOrder: String(item?.sortOrder ?? 1) }); const valid = Boolean(values.name.trim() && /^#[0-9a-fA-F]{6}$/.test(values.color) && Number(values.sortOrder) >= 0); const save = async () => { if (!valid) return; const data = { name: values.name.trim(), color: values.color, type: values.type || null, default: values.default, canArchive: values.canArchive, sortOrder: Number(values.sortOrder), permissionId: item?.permissionId ?? null }; try { if (item) await updateMutation.mutateAsync({ id: item.id, data }); else await createMutation.mutateAsync(data); onClose(); } catch (error) { showToast({ variant: 'danger', description: getApiErrorMessage(error, t('operation_failed')) }); } }; return <FormModal open={open} title={t(item ? 'edit' : 'add')} valid={valid} loading={createMutation.isPending || updateMutation.isPending} onClose={onClose} onSave={save}><Input label={t('name')} value={values.name} onChange={(event) => setValues((current) => ({ ...current, name: event.target.value }))} /><Input label={t('color')} value={values.color} onChange={(event) => setValues((current) => ({ ...current, color: event.target.value }))} /><Input label={t('type')} value={values.type} onChange={(event) => setValues((current) => ({ ...current, type: event.target.value }))} /><Input label={t('sort_order')} type="number" value={values.sortOrder} onChange={(event) => setValues((current) => ({ ...current, sortOrder: event.target.value }))} /><ToggleField label={t('default')} checked={values.default} onChange={(defaultValue) => setValues((current) => ({ ...current, default: defaultValue }))} /><ToggleField label={t('can_archive')} checked={values.canArchive} onChange={(canArchive) => setValues((current) => ({ ...current, canArchive }))} /></FormModal>; }
function CategoryForm({ open, item, onClose }: { open: boolean; item: TaskCategoryDto | null; onClose: () => void }) { const { t } = useTranslation('projects'); const { showToast } = useToast(); const createMutation = useCreateTaskCategoryMutation(); const updateMutation = useUpdateTaskCategoryMutation(); const [values, setValues] = useState({ name: item?.name ?? '', color: item?.color ?? '#3f6d6a', hasText: item?.hasText ?? false, hasAttachments: item?.hasAttachments ?? false, hasPrices: item?.hasPrices ?? false }); const valid = Boolean(values.name.trim() && /^#[0-9a-fA-F]{6}$/.test(values.color)); const save = async () => { if (!valid) return; const data = { name: values.name.trim(), color: values.color, hasText: values.hasText, hasAttachments: values.hasAttachments, hasPrices: values.hasPrices }; try { if (item) await updateMutation.mutateAsync({ id: item.id, data }); else await createMutation.mutateAsync(data); onClose(); } catch (error) { showToast({ variant: 'danger', description: getApiErrorMessage(error, t('operation_failed')) }); } }; return <FormModal open={open} title={t(item ? 'edit' : 'add')} valid={valid} loading={createMutation.isPending || updateMutation.isPending} onClose={onClose} onSave={save}><Input label={t('name')} value={values.name} onChange={(event) => setValues((current) => ({ ...current, name: event.target.value }))} /><Input label={t('color')} value={values.color} onChange={(event) => setValues((current) => ({ ...current, color: event.target.value }))} /><ToggleField label={t('text')} checked={values.hasText} onChange={(hasText) => setValues((current) => ({ ...current, hasText }))} /><ToggleField label={t('attachments')} checked={values.hasAttachments} onChange={(hasAttachments) => setValues((current) => ({ ...current, hasAttachments }))} /><ToggleField label={t('prices')} checked={values.hasPrices} onChange={(hasPrices) => setValues((current) => ({ ...current, hasPrices }))} /></FormModal>; }
function FormModal({ open, title, valid, loading, onClose, onSave, children }: { open: boolean; title: string; valid: boolean; loading: boolean; onClose: () => void; onSave: () => void; children: React.ReactNode }) { const { t } = useTranslation('projects'); return <Modal open={open} setOpen={(next) => !next && onClose()} title={title} footer={<><SecondaryButton onClick={onClose}>{t('cancel')}</SecondaryButton><PrimaryButton disabled={!valid} isSubmitting={loading} onClick={onSave}>{t('save')}</PrimaryButton></>}><div className="grid gap-4 sm:grid-cols-2">{children}</div></Modal>; }
function ToggleField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex min-h-[52px] items-center justify-between rounded-lg border border-gray-light-500 px-4 dark:border-dark-card-border"><span className="text-sm">{label}</span><Toggle checked={checked} onChange={onChange} /></div>; }
